import { Box, CircularProgress, Container, Typography } from "@mui/material";
import Head from "next/head";
import axios from "axios";
import { useRouter } from "next/router";
import React, { useEffect, useState } from "react";

function Post() {
  const [post, setPost] = useState({});
  const [isLoading, setIsLoading] = useState(true);
  const router = useRouter();
  const id = router.query.id;

  async function getSinglePost() {
    const response = await axios.get(`/api/post/${id}`);
    setPost(response.data);
  }
  useEffect(() => {
    if (!id) {
      return;
    }
    getSinglePost();
    setTimeout(() => {
      setIsLoading(false);
    }, 1000);
  }, [id]);
  return (
    <>
      <Head>
        <title>Detrator</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {!isLoading ? (
        <Box sx={{ m: 2, mt: 6, border: 1, borderRadius: "12px", p: 1 }}>
          <Typography sx={{ fontWeight: "bold", fontSize: 40, my: 4, mx: 2 }}>
            {post && post?.title}
          </Typography>
          <Typography sx={{ my: 4, mx: 2, fontSize: 20 }}>
            {post?.body}
          </Typography>
          <Box
            sx={{
              display: "flex",
              alignItems: "center",
              mx: 2,
              mb: 4,
              flexWrap: "wrap",
            }}
          >
            <Typography>Tags: </Typography>
            {post?.tags?.map((e) => {
              return (
                <Box
                  sx={{ mx: 2, border: 1, borderRadius: "12px", p: 1 }}
                  key={e}
                >
                  <Typography>{e}</Typography>
                </Box>
              );
            })}
          </Box>
        </Box>
      ) : (
        <Box
          display="flex"
          justifyContent="center"
          alignItems="center"
          minHeight="100vh"
        >
          <CircularProgress sx={{ color: "orange" }} />
        </Box>
      )}
    </>
  );
}

export default Post;
